### PR TITLE
Optimize images for shrinkray-1

### PR DESCRIPTION
**Pull request by sayanee**

### CODE REVIEW

**Comment by sayanee** [comment]
Images shrunk 20.76% (46347b -> 36726b)


* webuild/public/logo.png (17370b -> 12156b)
* webuild/public/apple-touch-icon.png (3248b -> 2897b)
* webuild/public/apple-touch-icon-precomposed.png (3248b -> 2897b)
* webuild/public/apple-touch-icon-114x114-precomposed.png (6539b -> 5428b)
* webuild/public/apple-touch-icon-144x144-precomposed.png (8481b -> 6869b)
* webuild/public/apple-touch-icon-57x57-precomposed.png (3248b -> 2897b)
* webuild/public/apple-touch-icon-72x72-precomposed.png (4213b -> 3582b)

**Comment by alyssaq** [comment]
Cool service

**Comment by sayanee** [comment]
Tip from @cheeaun's https://github.com/KopiJS/branding/pull/1 :tada:

**Comment by cheeaun** [comment]
:thumbsup:

**Pull request merged**
